pipeline{
  agent {
    label 'maven35'
  }

    environment{
      TOOLS = 'c2mvws-tools'
      DEV = 'c2mvws-dev'
      TEST = 'c2mvws-test'
      PROD = 'c2mvws-prod'

      REPO_NAME = 'educ-pen-request-api'
      OWNER = 'bcgov'
      JOB_NAME = 'master'
      TAG = 'dev'

      APP_NAME = 'pen-request-api'
      APP_DOMAIN = 'pathfinder.gov.bc.ca'

      SOURCE_REPO_RAW = 'https://github.com/${OWNER}/${REPO_NAME}/master'
      SOURCE_REPO_REF = 'master'
      SOURCE_REPO_URL = 'https://github.com/${OWNER}/${REPO_NAME}.git'

      TOOLS_HOST_ROUTE = "${APP_NAME}-${TOOLS}.${APP_DOMAIN}"
      DEV_HOST_ROUTE = "${APP_NAME}-${DEV}.${APP_DOMAIN}"
      TEST_HOST_ROUTE = "${APP_NAME}-${TEST}.${APP_DOMAIN}"
      PROD_HOST_ROUTE = "${APP_NAME}-${PROD}.${APP_DOMAIN}"
  }
  stages{
    stage('Build App') {
      steps {
        script {
          def pom = readMavenPom file: 'api/pom.xml'
          VERSION = pom.version
        }
        sh "mvn -f ./api/pom.xml -Dmaven.test.skip=true package"
      }
    }
    stage('Report to SonarQube') {
        steps {
            script{
                dir('api'){
                    sh "mvn sonar:sonar -Dsonar.host.url=http://sonarqube.c2mvws-tools.svc.cluster.local:9000 -Dsonar.login=dd9c4f7f4793fa8f285ce41f49977be331e93170"
                }
            }
        }
    }
    stage('Create Image Builder') {
      when {
        expression {
          openshift.withCluster() {
            return !openshift.selector("bc", "educ-pen-request-api-master").exists();
          }
        }
      }
      steps {
        script {
          openshift.withCluster() {
            openshift.newBuild("--name=educ-pen-request-api-master", "--image-stream=redhat-openjdk18-openshift:1.1", "--binary")
          }
        }
      }
    }
    stage('Build Image') {
      steps {
        script {
          openshift.withCluster() {
            openshift.selector("bc", "educ-pen-request-api-master").startBuild("--from-file=./api/target/penrequest-api-${VERSION}.jar", "--wait")
          }
        }
      }
      post {
        success {
          echo 'Cleanup BuildConfigs'
          script {
              openshift.withCluster() {
                openshift.withProject(TOOLS) {
                  def bcApi = openshift.selector('bc', "${REPO_NAME}-${JOB_NAME}")

                  if(bcApi.exists()) {
                      echo "Removing BuildConfig ${REPO_NAME}-${JOB_NAME}"
                      bcApi.delete()
                  }
                }
              }
            }
        }
        failure {
          echo 'Build stage failed'
        }
      }
    }
    stage('Promote to DEV') {
      steps {
        script {
          openshift.withCluster() {
            openshift.withProject(DEV) {
              echo "Tagging image"
              openshift.tag("${TOOLS}/${REPO_NAME}-${JOB_NAME}:latest", "${REPO_NAME}-${JOB_NAME}:${TAG}")
              def dcTemplate = openshift.process('-f',
                'tools/openshift/api.dc.yaml',
                "REPO_NAME=${REPO_NAME}",
                "JOB_NAME=${JOB_NAME}",
                "NAMESPACE=${DEV}",
                "APP_NAME=${APP_NAME}",
                "HOST_ROUTE=${DEV_HOST_ROUTE}",
                "TAG=${TAG}"
              )

              echo "Applying Deployment ${REPO_NAME}"
              def dc = openshift.apply(dcTemplate).narrow('dc')

              echo "Waiting for deployment to roll out"
              // Wait for deployments to roll out
              timeout(10) {
                dc.rollout().status('--watch=true')
              }
            }
          }
        }
      }
    }
    stage('Promote to TEST') {
      steps {
        script {
          openshift.withCluster() {
            openshift.withProject(TEST) {
              echo "Tagging image"
              openshift.tag("${TOOLS}/${REPO_NAME}-${JOB_NAME}:latest", "${REPO_NAME}-${JOB_NAME}:${TAG}")
              def dcTemplate = openshift.process('-f',
                'tools/openshift/api.dc.yaml',
                "REPO_NAME=${REPO_NAME}",
                "JOB_NAME=${JOB_NAME}",
                "NAMESPACE=${TEST}",
                "APP_NAME=${APP_NAME}",
                "HOST_ROUTE=${TEST_HOST_ROUTE}",
                "TAG=${TAG}"
              )

              echo "Applying Deployment ${REPO_NAME}"
              def dc = openshift.apply(dcTemplate).narrow('dc')

              echo "Waiting for deployment to roll out"
              // Wait for deployments to roll out
              timeout(10) {
                dc.rollout().status('--watch=true')
              }
            }
          }
        }
      }
    }
  }
}
