---
apiVersion: v1
kind: Template
labels:
  template: 'educ-pen-request-api-template'
metadata:
  name: 'educ-pen-request-api-template'
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      creationTimestamp:
      labels:
        build: "educ-pen-request-api-master"
      name: "educ-pen-request-api-master"
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      creationTimestamp:
      labels:
        build: "educ-pen-request-api"
      name: "educ-pen-request-api-master"
      namespace: mvubjx-tools
    spec:
      completionDeadlineSeconds: 1200
      successfulBuildsHistoryLimit: 3
      failedBuildsHistoryLimit: 3
      nodeSelector:
      output:
        to:
          kind: ImageStreamTag
          name: "educ-pen-request-api-master:latest"
      postCommit: {}
      resources:
        requests:
          cpu: 4000m
          memory: 2Gi
        limits:
          cpu: 8000m
          memory: 4Gi
        runPolicy: SerialLatestOnly
      source:
        git:
          ref: feature/docker
          uri: 'https://github.com/bcgov/EDUC-PEN-REQUEST-API'
        type: Git
      strategy:
        dockerStrategy:
          env:
            - name: BUILD_LOGLEVEL
              value: '2'
        type: Docker