---
apiVersion: v1
kind: Template
labels:
  template: 'educ-pen-request-api-template'
metadata:
  name: 'educ-pen-request-api-template'
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        build: educ-pen-request-pipeline
      name: educ-pen-request-pipeline
      namespace: c2mvws-tools
    spec:
      completionDeadlineSeconds: 1200
        successfulBuildsHistoryLimit: 3
        failedBuildsHistoryLimit: 3
        nodeSelector:
        output:
          to:
            kind: ImageStreamTag
            name: "educ-pen-request-api:latest"
        postCommit: {}
        resources:
          requests:
            cpu: 2000m
            memory: 2Gi
          limits:
            cpu: 4000m
            memory: 4Gi
        runPolicy: SerialLatestOnly
      source:
        git:
          ref: feature/docker
          uri: 'https://github.com/bcgov/EDUC-PEN-REQUEST-API'
        type: Git
      strategy:
        dockerStrategy:
          env:
            - name: BUILD_LOGLEVEL
              value: '2'
        type: Docker