name: API Integration Test

on:
  repository_dispatch:
    types: [integration-test]
  workflow_dispatch:  
jobs:
  integration_test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: oracle
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run integration tests
        run: mvn -f pom.xml clean test-compile failsafe:integration-test
        env:
          soam_discovery_url: ${{ secrets.SOAM_DISCOVERY_URL }}
          soam_client_id: ${{ secrets.SOAM_CLIENT_ID }}
          soam_client_secret: ${{ secrets.SOAM_CLIENT_SECRET }}
          api_url: ${{ secrets.API_URL }}